apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui
spec:
  template:
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - guestbook-ui
            topologyKey: "kubernetes.io/hostname"